### PR TITLE
add the stringrev program

### PR DESCRIPTION
**Pull request by atchuthautomation**
I have completed string code please check once ...

### CODE REVIEW

**Comment by Devicky125143** [comment]
kk atchuth nice implementation ..but add the printing statements

**Comment by atchuthautomation** [comment]
Kk boss.. I will

**Comment by Devicky125143** [comment]
kk all the best

**Comment by atchuthautomation** [comment]
Thankyou boss

**Comment by atchuthautomation** [comment]
Boss I added the printing statements please check

**Comment by Devicky125143** [comment]
kk atchuth good keep it up 
 merge the branches

**Comment by atchuthautomation** [comment]
Kk boss

**Comment by atchuthautomation** [comment]
Boss I added one extra program please check once and approve me

**Comment by Devicky125143** [comment]
kk atchuth i will .....

**Comment by atchuthautomation** [comment]
Kk Boss

**Comment by Devicky125143** [comment]
kk atchuth nice good merge it now .... k

**Pull request merged**
